%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#EBF2FA',
      'primaryTextColor': '#2B65A9',
      'primaryBorderColor': '#2B65A9',
      'lineColor': '#D43F3A',
      'secondaryColor': '#2B65A9',
      'tertiaryColor': '#EBF2FA',
      'secondaryTextColor': '#FFFFFF',
      'mainBkg': '#FFFFFF',
      'nodeBorder': '#2B65A9',
      'actorBorder': '#A52A2A',
      'clusterBkg': '#F0F8FF'
    }
  }
}%%
graph TD;

    %% STAGE 1: PRE-TRADE & ORDER GENERATION
    subgraph "STAGE 1: Pre-Trade & Order Generation (Buy-Side)"
        A1["<font size=4><b>Investment Idea & Analysis</b></font><br>Portfolio Manager (PM) formulates strategy.<br>Pre-trade compliance & risk checks are performed against mandates."]
        A2["<font size=4><b>Order Creation</b></font><br>PM creates a large 'parent' order in the Order Management System (OMS)."]
        A3["<font size=4><b>Broker Selection</b></font><br>The trader selects an executing broker-dealer.<br>The parent order is sent to the broker, typically via FIX protocol."]
        A1 --> A2 --> A3
    end

    %% STAGE 2: EXECUTION & CENTRAL CLEARING (THE CYCLICAL ENGINE)
    subgraph "STAGE 2: Trade Execution & Central Clearing (Sell-Side & Market Infrastructure)"
        B1["<font size=4><b>Broker Receives Institutional Order</b></font><br>The broker-dealer's trading desk receives the large parent order from the Investment Manager."]
        
        subgraph "Execution Loop (Intra-Day)"
            B2["<b>Smart Order Router (SOR)</b><br>The parent order is fed into the broker's SOR.<br>The SOR algorithmically breaks the parent order into multiple smaller 'child' orders to find liquidity and achieve Best Execution."]
            
            B3{"<b>Execution Venues</b><br>SOR routes child orders to various destinations:"}
            style B3 fill:#FFF3CD,stroke:#FFA500
            
            B4["- <b>Exchanges</b> (e.g., NYSE, Nasdaq)<br>- <b>Alternative Trading Systems (ATSs)</b><br>- <b>Broker's own Dark Pool / Internalizer</b>"]
            
            B5["<b>Trade Execution Occurs</b><br>Child orders are executed against various counterparties (other brokers, market makers).<br>An execution report ('fill') is generated for each executed child order."]
        
            B6["<b>Real-Time Reporting (Dual Path)</b>"]
            
            B7["<b>Path 1: Report to Broker</b><br>Execution venues report fills back to the broker's SOR in real-time."]
            B8["<b>Path 2: Report to NSCC</b><br>Simultaneously, execution venues report the locked-in trade data to NSCC's<br><b>Continuous Trade Settlement (CTS) / Universal Trade Capture (UTC)</b> system."]
            
            B9["<b>Aggregation of Fills</b><br>The broker's SOR aggregates all child order fills.<br>When the parent order is complete, a final execution notice (at average price) is sent to the Investment Manager's OMS."]
            B2 --> B3 --> B4 --> B5 --> B6
            B6 --> B7 --> B9
            B6 --> B8
            B9 --> B2
        end

        B10["<font size=4><b>NSCC Night Cycle: CNS Processing (End of Day)</b></font><br>All trades submitted to CTS throughout the day are processed by the Continuous Net Settlement (CNS) engine."]
        style B10 fill:#D5E8D4,stroke:#82B366
        
        B11["<b>1. Novation & Netting</b><br>NSCC becomes the Central Counterparty (CCP) for all eligible trades, mitigating counterparty risk.<br>It performs multilateral netting, boiling down all of a member's buys and sells in a single security to one final net 'long' (receive) or 'short' (deliver) position for T+1 settlement."]
        
        B12["<b>2. Balance Order Generation</b><br>To reconcile the broker's net CNS obligation with its underlying institutional client trades, NSCC generates <b>Balance Orders</b>.<br>A Balance Order is a settlement instruction that tells the broker the specific DVP/RVP deliveries they must make to institutional custodians to satisfy their net position."]
        style B12 fill:#F8CECC,stroke:#B85450

        A3 --> B1 --> B2
        B8 --> B10 --> B11 --> B12
    end

    %% STAGE 3: INSTITUTIONAL MATCHING & AFFIRMATION (PARALLEL PROCESS)
    subgraph "STAGE 3: Institutional Allocation & Affirmation (T+0)"
        C1["<font size=4><b>Allocation by Investment Manager (Post-Execution)</b></font><br>The IM receives the final execution notice from the broker (from step B9).<br>The PM allocates the block trade to the individual underlying funds in their OMS."]
        
        C2["<b>Submission to Central Matching Platform (e.g., DTCC's CTM)</b><br>This institutional matching process runs in parallel to the broker-to-broker clearing at NSCC."]
        
        C3["<b>Buy-Side Submission:</b><br>Investment Manager submits their allocation details to CTM."]
        C4["<b>Sell-Side Submission:</b><br>Broker-Dealer submits their trade confirmation details to CTM."]
        
        C5["<b>Automated SSI Enrichment via ALERT</b><br>CTM automatically enriches the trade with Standing Settlement Instructions (SSIs) from the DTCC ALERT platform, adding the correct custodian and account details."]
        
        C6["<font size=4><b>Central Matching & Affirmation</b></font><br><b>1. Matching:</b> CTM compares and matches the buy-side and sell-side details. A 'Match Agreed' status creates the binding trade record.<br><b>2. Auto-Affirmation:</b> The matched trade is automatically sent to TradeSuite ID, which affirms the trade on behalf of the institution.<br><b>This creates the authoritative instruction for the custodian to expect a DVP/RVP settlement.</b>"]
        
        B9 --> C1 --> C2
        C2 --> C3 --> C5
        C2 --> C4
        C5 & C4 --> C6
    end

    %% STAGE 4: SETTLEMENT CONVERGENCE
    subgraph "STAGE 4: Settlement at DTC (T+1)"
        D1["<font size=4><b>Convergence of Instructions</b></font><br>The two parallel workflows must now converge for settlement to occur."]
        style D1 fill:#E1D5E7,stroke:#9673A6
        
        D2["<b>Broker's View:</b><br>Receives the <b>Balance Order</b> from NSCC, which dictates the specific institutional deliveries required to meet its net CNS obligation."]
        
        D3["<b>Custodian's View:</b><br>Receives the <b>Affirmed Trade Confirmation</b> from TradeSuite ID/CTM, which serves as the authorization to accept delivery of securities and release payment."]
        
        B12 --> D1
        C6 --> D1
        D1 --> D2
        D1 --> D3

        D4["<font size=4><b>DVP/RVP Settlement at The Depository Trust Company (DTC)</b></font><br>The broker-dealer initiates a <b>Delivery vs. Payment (DVP)</b> instruction at DTC."]
        
        D5["<b>DTC Processing:</b><br><b>1. Authorization:</b> DTC validates the DVP instruction against the custodian's authorization (which is based on the affirmed trade).<br><b>2. Simultaneous Transfer:</b> DTC simultaneously debits the securities from the broker's DTC account and credits them to the custodian's DTC account, while also debiting cash from the custodian's settlement bank and crediting the broker's settlement bank.<br>This is a risk-free, atomic transaction."]
        
        D6["<b>Settlement Finality</b><br>The trade is now settled. Legal title of the securities has transferred."]
        D2 & D3 --> D4 --> D5 --> D6
    end
    
    %% STAGE 5: POST-SETTLEMENT
    subgraph "STAGE 5: Post-Settlement & Reconciliation"
        E1{"<b>Settlement Status</b>"}
        D6 --> E1
        E2["<font size=4><b>Successful Settlement</b></font><br><b>Custody:</b> Custodian holds assets and manages asset servicing (corporate actions, dividends).<br><b>Reconciliation:</b> All parties (IM, Broker, Custodian) reconcile their internal records."]
        E3["<font size=4><b>Settlement Failure</b></font><br><b>Cause:</b> Insufficient securities or funds, operational error.<br><b>Resolution:</b> Parties investigate and resolve. May involve securities lending or, in rare cases, a formal buy-in process."]
        E1 -- "Success" --> E2
        E1 -- "Fail" --> E3
    end
